DEF rSVBK EQU $ff70
DEF wPokedexSelectedState EQU $c727
DEF B_wPokedexSelectedState EQU $00
DEF wBGPals1 EQU $d000
DEF B_wBGPals1 EQU $05
DEF Pokedex_BlackOutBG EQU $5581
DEF B_Pokedex_BlackOutBG EQU $10
DEF FarCall EQU $0008
DEF B_FarCall EQU $00
DEF wPokedexWRAM0Scratch EQU $c800
DEF B_wPokedexWRAM0Scratch EQU $00
DEF wPokedexWRAM0ScratchEnd EQU $cd14
DEF B_wPokedexWRAM0ScratchEnd EQU $00
DEF hCGB EQU $ffe6
DEF B_hCGB EQU $00
DEF wCurPartySpecies EQU $d10a
DEF B_wCurPartySpecies EQU $01
DEF wPokedexResidentFootprintSpecies EQU $c720
DEF B_wPokedexResidentFootprintSpecies EQU $00
DEF wTilemap EQU $c4a0
DEF B_wTilemap EQU $00
DEF LowVolume EQU $3950
DEF B_LowVolume EQU $00
DEF PokedexSelectedMon_BeginWarmTransition EQU $6ca2
DEF B_PokedexSelectedMon_BeginWarmTransition EQU $a0
DEF Pokedex_DrawResidentFootprint EQU $4f02
DEF B_Pokedex_DrawResidentFootprint EQU $10
DEF wBaseType1 EQU $d23f
DEF B_wBaseType1 EQU $01
DEF wBaseType2 EQU $d240
DEF B_wBaseType2 EQU $01
DEF Pokedex_LoadDescriptionTypeGFX_PlaceType EQU $6fa2
DEF B_Pokedex_LoadDescriptionTypeGFX_PlaceType EQU $a0
DEF wPokedexSelectedSpecies EQU $c725
DEF B_wPokedexSelectedSpecies EQU $00
DEF Pokedex_LoadCurrentFootprint EQU $5652
DEF B_Pokedex_LoadCurrentFootprint EQU $10
INCLUDE "/Users/jakeadams/Documents/GitHub/Pokemon-Resplendent-Crystal/build/dex-icon-buffer-preflight/icon-buffer.asm"
