DEF TILE_1BPP_SIZE EQU TILE_SIZE / 2 ; bytes

DEF PALRGB_WHITE EQU palred 31 + palgreen 31 + palblue 31 ; $7fff

DEF METATILE_WIDTH EQU 4 ; tiles
DEF SCREEN_META_WIDTH  EQU 6 ; metatiles
DEF SCREEN_META_HEIGHT EQU 5 ; metatiles
DEF SURROUNDING_WIDTH  EQU SCREEN_META_WIDTH * METATILE_WIDTH ; tiles
DEF SURROUNDING_HEIGHT EQU SCREEN_META_HEIGHT * METATILE_WIDTH ; tiles
DEF MAP_CONNECTION_PADDING_WIDTH EQU 3 ; metatiles

DEF HP_BAR_LENGTH  EQU 6 ; tiles
DEF EXP_BAR_LENGTH EQU 8 ; tiles
DEF HP_BAR_LENGTH_PX  EQU HP_BAR_LENGTH  * TILE_WIDTH ; pixels
DEF EXP_BAR_LENGTH_PX EQU EXP_BAR_LENGTH * TILE_WIDTH ; pixels

; Battle HUD vTiles2 layout.
DEF BATTLE_HUD_EXP_TAIL_LEFT_TILE       EQU $55
DEF BATTLE_HUD_EXP_TAIL_RIGHT_TILE      EQU $56
; $57-$5c are left free for future HUD graphics.
DEF BATTLE_HUD_FREE_FIRST_TILE          EQU $57
DEF BATTLE_HUD_FREE_TILES               EQU 6
DEF BATTLE_HUD_EXP_PARTIAL_TILE         EQU $5d ; uses $5d-$63
DEF BATTLE_HUD_HP_LABEL_TILE            EQU $64 ; uses $64-$65
DEF BATTLE_HUD_BAR_EMPTY_TILE           EQU $66
DEF BATTLE_HUD_HP_PARTIAL_TILE          EQU $67 ; uses $67-$6d
DEF BATTLE_HUD_LEVEL_TILE               EQU '<LV>'
DEF BATTLE_HUD_BAR_FULL_TILE            EQU $6f
DEF BATTLE_HUD_ENEMY_HP_END_TILE        EQU $70
DEF BATTLE_HUD_PLAYER_HP_END_TILE       EQU $71
DEF BATTLE_HUD_ENEMY_LEFT_TILE          EQU $72
DEF BATTLE_HUD_PLAYER_BOTTOM_LEFT_TILE  EQU $73
DEF BATTLE_HUD_PLAYER_RIGHT_TILE        EQU $74
DEF BATTLE_HUD_ENEMY_BOTTOM_LEFT_TILE   EQU $75
DEF BATTLE_HUD_BOTTOM_TILE              EQU $76
DEF BATTLE_HUD_PLAYER_BOTTOM_RIGHT_TILE EQU $77
DEF BATTLE_HUD_ENEMY_BOTTOM_RIGHT_TILE  EQU $78

; Battle HUD marker tiles stored in vTiles1 font gaps.
DEF BATTLE_HUD_PARTY_ICON_TILE       EQU $ce
DEF BATTLE_HUD_CAUGHT_ICON_TILE      EQU $cf
DEF BATTLE_HUD_PARTY_ICON_DEST_TILE  EQU BATTLE_HUD_PARTY_ICON_TILE - $80
DEF BATTLE_HUD_CAUGHT_ICON_DEST_TILE EQU BATTLE_HUD_CAUGHT_ICON_TILE - $80

; GetHPPal return values (see home/tilemap.asm)
DEF HP_GREEN  EQU 0
DEF HP_YELLOW EQU 1
DEF HP_RED    EQU 2

DEF SPRITE_GFX_LIST_CAPACITY EQU 32 ; see wUsedSprites

; PokeAnims indexes (see engine/gfx/pic_animation.asm)
	const_def
	const ANIM_MON_SLOW
	const ANIM_MON_NORMAL
	const ANIM_MON_MENU
	const ANIM_MON_TRADE
	const ANIM_MON_EVOLVE
	const ANIM_MON_HATCH
	const ANIM_MON_HOF
	const ANIM_MON_EGG1
	const ANIM_MON_EGG2

DEF OAM_YCOORD_HIDDEN EQU 160 ; hides an OAM offscreen
