; Move category icons
	const_def
	const MOVE_CATEGORY_PHYSICAL
	const MOVE_CATEGORY_SPECIAL
	const MOVE_CATEGORY_STATUS
DEF NUM_MOVE_CATEGORIES EQU const_value

; Status condition icons
	const_def
	const STATUS_ICON_BURN
	const STATUS_ICON_FAINTED
	const STATUS_ICON_FREEZE
	const STATUS_ICON_PARALYSIS
	const STATUS_ICON_POISON
	const STATUS_ICON_SLEEP
	const STATUS_ICON_TOXIC
DEF NUM_STATUS_ICONS EQU const_value
DEF STATUS_ICON_TILES EQU 3 ; 24x8, one row of three 8x8 tiles
DEF STATUS_ICON_NONE EQU $ff

DEF BATTLE_STATUS_ICON_PLAYER_TILE EQU $78 ; uses $78-$7a in VRAM bank 1
DEF BATTLE_STATUS_ICON_ENEMY_TILE  EQU $7b ; uses $7b-$7d in VRAM bank 1
DEF BATTLE_STATUS_ICON_ATTR EQU $08 | PAL_BATTLE_BG_5 ; VRAM bank 1, BG palette 5
DEF BATTLE_STATUS_ICON_PLAYER_X EQU 14
DEF BATTLE_STATUS_ICON_PLAYER_Y EQU 8
DEF BATTLE_STATUS_ICON_ENEMY_X EQU 6
DEF BATTLE_STATUS_ICON_ENEMY_Y EQU 1

; LoadMenuMonIcon.Jumptable indexes (see engine/gfx/mon_icons.asm)
	const_def
	const MONICON_PARTYMENU
	const MONICON_NAMINGSCREEN
	const MONICON_MOVES
	const MONICON_TRADE
	const MONICON_MOBILE1
	const MONICON_MOBILE2
	const MONICON_UNUSED

; party menu icon palettes
	const_def
	const PAL_ICON_RED    ; 0
	const PAL_ICON_BLUE   ; 1
	const PAL_ICON_GREEN  ; 2
	const PAL_ICON_BROWN  ; 3
	const PAL_ICON_PINK   ; 4
	const PAL_ICON_GRAY   ; 5
	const PAL_ICON_TEAL   ; 6
	const PAL_ICON_PURPLE ; 7
