DEF APRICORN_SHARED_BLACK_R EQU 00
DEF APRICORN_SHARED_BLACK_G EQU 00
DEF APRICORN_SHARED_BLACK_B EQU 00
DEF APRICORN_SHARED_WHITE_R EQU 31
DEF APRICORN_SHARED_WHITE_G EQU 31
DEF APRICORN_SHARED_WHITE_B EQU 31
DEF APRICORN_SHARED_BROWN_R EQU 20
DEF APRICORN_SHARED_BROWN_G EQU 12
DEF APRICORN_SHARED_BROWN_B EQU 05
DEF APRICORN_EMPTY_STEM_R EQU 09
DEF APRICORN_EMPTY_STEM_G EQU 09
DEF APRICORN_EMPTY_STEM_B EQU 09
DEF APRICORN_EMPTY_BODY_R EQU 16
DEF APRICORN_EMPTY_BODY_G EQU 16
DEF APRICORN_EMPTY_BODY_B EQU 16
DEF APRICORN_BORDER_DARK_R EQU 26
DEF APRICORN_BORDER_DARK_G EQU 21
DEF APRICORN_BORDER_DARK_B EQU 00
DEF APRICORN_BORDER_LIGHT_R EQU 31
DEF APRICORN_BORDER_LIGHT_G EQU 29
DEF APRICORN_BORDER_LIGHT_B EQU 08

; Palette 0: text, black/white title tiles, and empty Apricorns
	RGB APRICORN_SHARED_WHITE_R, APRICORN_SHARED_WHITE_G, APRICORN_SHARED_WHITE_B
	RGB APRICORN_EMPTY_STEM_R, APRICORN_EMPTY_STEM_G, APRICORN_EMPTY_STEM_B
	RGB APRICORN_EMPTY_BODY_R, APRICORN_EMPTY_BODY_G, APRICORN_EMPTY_BODY_B
	RGB APRICORN_SHARED_BLACK_R, APRICORN_SHARED_BLACK_G, APRICORN_SHARED_BLACK_B

; Palette 1: yellow side borders
	RGB APRICORN_SHARED_WHITE_R, APRICORN_SHARED_WHITE_G, APRICORN_SHARED_WHITE_B
	RGB APRICORN_BORDER_LIGHT_R, APRICORN_BORDER_LIGHT_G, APRICORN_BORDER_LIGHT_B
	RGB APRICORN_BORDER_DARK_R, APRICORN_BORDER_DARK_G, APRICORN_BORDER_DARK_B
	RGB APRICORN_SHARED_BLACK_R, APRICORN_SHARED_BLACK_G, APRICORN_SHARED_BLACK_B

; Palette 2: blue Apricorn
	RGB APRICORN_SHARED_WHITE_R, APRICORN_SHARED_WHITE_G, APRICORN_SHARED_WHITE_B
	RGB APRICORN_SHARED_BROWN_R, APRICORN_SHARED_BROWN_G, APRICORN_SHARED_BROWN_B
	RGB 09, 00, 31
	RGB APRICORN_SHARED_BLACK_R, APRICORN_SHARED_BLACK_G, APRICORN_SHARED_BLACK_B

; Palette 3: green Apricorn
	RGB APRICORN_SHARED_WHITE_R, APRICORN_SHARED_WHITE_G, APRICORN_SHARED_WHITE_B
	RGB APRICORN_SHARED_BROWN_R, APRICORN_SHARED_BROWN_G, APRICORN_SHARED_BROWN_B
	RGB 00, 20, 07
	RGB APRICORN_SHARED_BLACK_R, APRICORN_SHARED_BLACK_G, APRICORN_SHARED_BLACK_B

; Palette 4: red Apricorn
	RGB APRICORN_SHARED_WHITE_R, APRICORN_SHARED_WHITE_G, APRICORN_SHARED_WHITE_B
	RGB APRICORN_SHARED_BROWN_R, APRICORN_SHARED_BROWN_G, APRICORN_SHARED_BROWN_B
	RGB 31, 00, 00
	RGB APRICORN_SHARED_BLACK_R, APRICORN_SHARED_BLACK_G, APRICORN_SHARED_BLACK_B

; Palette 5: yellow Apricorn
	RGB APRICORN_SHARED_WHITE_R, APRICORN_SHARED_WHITE_G, APRICORN_SHARED_WHITE_B
	RGB APRICORN_SHARED_BROWN_R, APRICORN_SHARED_BROWN_G, APRICORN_SHARED_BROWN_B
	RGB 31, 31, 00
	RGB APRICORN_SHARED_BLACK_R, APRICORN_SHARED_BLACK_G, APRICORN_SHARED_BLACK_B

; Palette 6: pink Apricorn
	RGB APRICORN_SHARED_WHITE_R, APRICORN_SHARED_WHITE_G, APRICORN_SHARED_WHITE_B
	RGB APRICORN_SHARED_BROWN_R, APRICORN_SHARED_BROWN_G, APRICORN_SHARED_BROWN_B
	RGB 31, 10, 14
	RGB APRICORN_SHARED_BLACK_R, APRICORN_SHARED_BLACK_G, APRICORN_SHARED_BLACK_B

; Palette 7: shared black/white Apricorns
	RGB APRICORN_SHARED_WHITE_R, APRICORN_SHARED_WHITE_G, APRICORN_SHARED_WHITE_B
	RGB APRICORN_SHARED_BROWN_R, APRICORN_SHARED_BROWN_G, APRICORN_SHARED_BROWN_B
	RGB APRICORN_SHARED_WHITE_R, APRICORN_SHARED_WHITE_G, APRICORN_SHARED_WHITE_B
	RGB APRICORN_SHARED_BLACK_R, APRICORN_SHARED_BLACK_G, APRICORN_SHARED_BLACK_B
