NightMusicTable:
	db MUSIC_NEW_BARK_TOWN,    MUSIC_NEW_BARK_TOWN_NIGHT
	db MUSIC_ROUTE_29,         MUSIC_ROUTE_29_NIGHT
	db MUSIC_CHERRYGROVE_CITY, MUSIC_CHERRYGROVE_CITY_NIGHT
	db MUSIC_ROUTE_30,         MUSIC_ROUTE_30_NIGHT
	db MUSIC_VIOLET_CITY,      MUSIC_VIOLET_CITY_NIGHT
	db MUSIC_AZALEA_TOWN,      MUSIC_AZALEA_TOWN_NIGHT
	db MUSIC_GOLDENROD_CITY,   MUSIC_GOLDENROD_CITY_NIGHT
	db MUSIC_ECRUTEAK_CITY,    MUSIC_ECRUTEAK_CITY_NIGHT
	db MUSIC_ROUTE_37,         MUSIC_ROUTE_37_NIGHT
	db MUSIC_LAKE_OF_RAGE,     MUSIC_LAKE_OF_RAGE_NIGHT
	db MUSIC_ROUTE_26,         MUSIC_ROUTE_26_NIGHT
	db MUSIC_ROUTE_3,          MUSIC_ROUTE_3_NIGHT
	db MUSIC_ROUTE_12,         MUSIC_ROUTE_12_NIGHT
	db MUSIC_CELADON_CITY,     MUSIC_CELADON_CITY_NIGHT
	db MUSIC_VERMILION_CITY,   MUSIC_VERMILION_CITY_NIGHT
	db MUSIC_PALLET_TOWN,      MUSIC_PALLET_TOWN_NIGHT
	db MUSIC_ROUTE_1,          MUSIC_ROUTE_1_NIGHT
	db MUSIC_LAVENDER_TOWN,    MUSIC_LAVENDER_TOWN_NIGHT
	db -1
