DEF rBGP EQU $ff47
DEF rOBP0 EQU $ff48
DEF rSVBK EQU $ff70
DEF rVBK EQU $ff4f
DEF rLY EQU $ff44
DEF rBGPI EQU $ff68
DEF rBGPD EQU $ff69
DEF rHDMA1 EQU $ff51
DEF rHDMA2 EQU $ff52
DEF rHDMA3 EQU $ff53
DEF rHDMA4 EQU $ff54
DEF rHDMA5 EQU $ff55
DEF CopyPals EQU $0b82
DEF B_CopyPals EQU $00
DEF Pokedex_PrepareSelectedMonTiles EQU $55ff
DEF B_Pokedex_PrepareSelectedMonTiles EQU $10
DEF Pokedex_CommitPreparedSelectedMonGFX EQU $5bb8
DEF B_Pokedex_CommitPreparedSelectedMonGFX EQU $77
DEF PokedexSelectedMon_BeginHiddenTransition EQU $6c3e
DEF B_PokedexSelectedMon_BeginHiddenTransition EQU $a0
DEF PokedexSelectedMon_Reveal EQU $6c78
DEF B_PokedexSelectedMon_Reveal EQU $a0
DEF Pokedex_CopyBackingToBG EQU $562f
DEF B_Pokedex_CopyBackingToBG EQU $77
DEF wOBPals1 EQU $d040
DEF B_wOBPals1 EQU $05
DEF wOBPals2 EQU $d0c0
DEF B_wOBPals2 EQU $05
DEF wBGPals2 EQU $d080
DEF B_wBGPals2 EQU $05
DEF wPokedexSelectedState EQU $c727
DEF B_wPokedexSelectedState EQU $00
DEF wPokedexOwnerAttrmapBuffer EQU $d240
DEF B_wPokedexOwnerAttrmapBuffer EQU $03
DEF wPokedexOwnerTilemapBuffer EQU $d000
DEF B_wPokedexOwnerTilemapBuffer EQU $03
DEF hCGB EQU $ffe6
DEF B_hCGB EQU $00
DEF hCGBPalUpdate EQU $ffe5
DEF B_hCGBPalUpdate EQU $00
DEF wPokedexSelectedBGPaletteDirty EQU $c72c
DEF B_wPokedexSelectedBGPaletteDirty EQU $00
DEF wPokedexSelectedOBJPaletteDirty EQU $c72d
DEF B_wPokedexSelectedOBJPaletteDirty EQU $00
DEF FarCall EQU $0008
DEF B_FarCall EQU $00
INCLUDE "/Users/jakeadams/Documents/GitHub/Pokemon-Resplendent-Crystal/tools/dex_timing/probes/internal_transition_prototype.asm"
