BitmasksPointers:
	table_width 3
	dba BulbasaurBitmasks
	dba IvysaurBitmasks
	dba VenusaurBitmasks
	dba CharmanderBitmasks
	dba CharmeleonBitmasks
	dba CharizardBitmasks
	dba SquirtleBitmasks
	dba WartortleBitmasks
	dba BlastoiseBitmasks
	dba CaterpieBitmasks
	dba MetapodBitmasks
	dba ButterfreeBitmasks
	dba WeedleBitmasks
	dba KakunaBitmasks
	dba BeedrillBitmasks
	dba PidgeyBitmasks
	dba PidgeottoBitmasks
	dba PidgeotBitmasks
	dba RattataBitmasks
	dba RaticateBitmasks
	dba SpearowBitmasks
	dba FearowBitmasks
	dba EkansBitmasks
	dba ArbokBitmasks
	dba PikachuBitmasks
	dba RaichuBitmasks
	dba SandshrewBitmasks
	dba SandslashBitmasks
	dba NidoranFBitmasks
	dba NidorinaBitmasks
	dba NidoqueenBitmasks
	dba NidoranMBitmasks
	dba NidorinoBitmasks
	dba NidokingBitmasks
	dba ClefairyBitmasks
	dba ClefableBitmasks
	dba VulpixBitmasks
	dba NinetalesBitmasks
	dba JigglypuffBitmasks
	dba WigglytuffBitmasks
	dba ZubatBitmasks
	dba GolbatBitmasks
	dba OddishBitmasks
	dba GloomBitmasks
	dba VileplumeBitmasks
	dba ParasBitmasks
	dba ParasectBitmasks
	dba VenonatBitmasks
	dba VenomothBitmasks
	dba DiglettBitmasks
	dba DugtrioBitmasks
	dba MeowthBitmasks
	dba PersianBitmasks
	dba PsyduckBitmasks
	dba GolduckBitmasks
	dba MankeyBitmasks
	dba PrimeapeBitmasks
	dba GrowlitheBitmasks
	dba ArcanineBitmasks
	dba PoliwagBitmasks
	dba PoliwhirlBitmasks
	dba PoliwrathBitmasks
	dba AbraBitmasks
	dba KadabraBitmasks
	dba AlakazamBitmasks
	dba MachopBitmasks
	dba MachokeBitmasks
	dba MachampBitmasks
	dba BellsproutBitmasks
	dba WeepinbellBitmasks
	dba VictreebelBitmasks
	dba TentacoolBitmasks
	dba TentacruelBitmasks
	dba GeodudeBitmasks
	dba GravelerBitmasks
	dba GolemBitmasks
	dba PonytaBitmasks
	dba RapidashBitmasks
	dba SlowpokeBitmasks
	dba SlowbroBitmasks
	dba MagnemiteBitmasks
	dba MagnetonBitmasks
	dba FarfetchDBitmasks
	dba DoduoBitmasks
	dba DodrioBitmasks
	dba SeelBitmasks
	dba DewgongBitmasks
	dba GrimerBitmasks
	dba MukBitmasks
	dba ShellderBitmasks
	dba CloysterBitmasks
	dba GastlyBitmasks
	dba HaunterBitmasks
	dba GengarBitmasks
	dba OnixBitmasks
	dba DrowzeeBitmasks
	dba HypnoBitmasks
	dba KrabbyBitmasks
	dba KinglerBitmasks
	dba VoltorbBitmasks
	dba ElectrodeBitmasks
	dba ExeggcuteBitmasks
	dba ExeggutorBitmasks
	dba CuboneBitmasks
	dba MarowakBitmasks
	dba HitmonleeBitmasks
	dba HitmonchanBitmasks
	dba LickitungBitmasks
	dba KoffingBitmasks
	dba WeezingBitmasks
	dba RhyhornBitmasks
	dba RhydonBitmasks
	dba ChanseyBitmasks
	dba TangelaBitmasks
	dba KangaskhanBitmasks
	dba HorseaBitmasks
	dba SeadraBitmasks
	dba GoldeenBitmasks
	dba SeakingBitmasks
	dba StaryuBitmasks
	dba StarmieBitmasks
	dba MrMimeBitmasks
	dba ScytherBitmasks
	dba JynxBitmasks
	dba ElectabuzzBitmasks
	dba MagmarBitmasks
	dba PinsirBitmasks
	dba TaurosBitmasks
	dba MagikarpBitmasks
	dba GyaradosBitmasks
	dba LaprasBitmasks
	dba DittoBitmasks
	dba EeveeBitmasks
	dba VaporeonBitmasks
	dba JolteonBitmasks
	dba FlareonBitmasks
	dba PorygonBitmasks
	dba OmanyteBitmasks
	dba OmastarBitmasks
	dba KabutoBitmasks
	dba KabutopsBitmasks
	dba AerodactylBitmasks
	dba SnorlaxBitmasks
	dba ArticunoBitmasks
	dba ZapdosBitmasks
	dba MoltresBitmasks
	dba DratiniBitmasks
	dba DragonairBitmasks
	dba DragoniteBitmasks
	dba MewtwoBitmasks
	dba MewBitmasks
	dba ChikoritaBitmasks
	dba BayleefBitmasks
	dba MeganiumBitmasks
	dba CyndaquilBitmasks
	dba QuilavaBitmasks
	dba TyphlosionBitmasks
	dba TotodileBitmasks
	dba CroconawBitmasks
	dba FeraligatrBitmasks
	dba SentretBitmasks
	dba FurretBitmasks
	dba HoothootBitmasks
	dba NoctowlBitmasks
	dba LedybaBitmasks
	dba LedianBitmasks
	dba SpinarakBitmasks
	dba AriadosBitmasks
	dba CrobatBitmasks
	dba ChinchouBitmasks
	dba LanturnBitmasks
	dba PichuBitmasks
	dba CleffaBitmasks
	dba IgglybuffBitmasks
	dba TogepiBitmasks
	dba TogeticBitmasks
	dba NatuBitmasks
	dba XatuBitmasks
	dba MareepBitmasks
	dba FlaaffyBitmasks
	dba AmpharosBitmasks
	dba BellossomBitmasks
	dba MarillBitmasks
	dba AzumarillBitmasks
	dba SudowoodoBitmasks
	dba PolitoedBitmasks
	dba HoppipBitmasks
	dba SkiploomBitmasks
	dba JumpluffBitmasks
	dba AipomBitmasks
	dba SunkernBitmasks
	dba SunfloraBitmasks
	dba YanmaBitmasks
	dba WooperBitmasks
	dba QuagsireBitmasks
	dba EspeonBitmasks
	dba UmbreonBitmasks
	dba MurkrowBitmasks
	dba SlowkingBitmasks
	dba MisdreavusBitmasks
	dba UnownBitmasks
	dba WobbuffetBitmasks
	dba GirafarigBitmasks
	dba PinecoBitmasks
	dba ForretressBitmasks
	dba DunsparceBitmasks
	dba GligarBitmasks
	dba SteelixBitmasks
	dba SnubbullBitmasks
	dba GranbullBitmasks
	dba QwilfishBitmasks
	dba ScizorBitmasks
	dba ShuckleBitmasks
	dba HeracrossBitmasks
	dba SneaselBitmasks
	dba TeddiursaBitmasks
	dba UrsaringBitmasks
	dba SlugmaBitmasks
	dba MagcargoBitmasks
	dba SwinubBitmasks
	dba PiloswineBitmasks
	dba CorsolaBitmasks
	dba RemoraidBitmasks
	dba OctilleryBitmasks
	dba DelibirdBitmasks
	dba MantineBitmasks
	dba SkarmoryBitmasks
	dba HoundourBitmasks
	dba HoundoomBitmasks
	dba KingdraBitmasks
	dba PhanpyBitmasks
	dba DonphanBitmasks
	dba Porygon2Bitmasks
	dba StantlerBitmasks
	dba SmeargleBitmasks
	dba TyrogueBitmasks
	dba HitmontopBitmasks
	dba SmoochumBitmasks
	dba ElekidBitmasks
	dba MagbyBitmasks
	dba MiltankBitmasks
	dba BlisseyBitmasks
	dba RaikouBitmasks
	dba EnteiBitmasks
	dba SuicuneBitmasks
	dba LarvitarBitmasks
	dba PupitarBitmasks
	dba TyranitarBitmasks
	dba LugiaBitmasks
	dba HoOhBitmasks
	dba CelebiBitmasks
	dba TreeckoBitmasks
	dba GrovyleBitmasks
	dba SceptileBitmasks
	dba TorchicBitmasks
	dba CombuskenBitmasks
	dba BlazikenBitmasks
	dba MudkipBitmasks
	dba MarshtompBitmasks
	dba SwampertBitmasks
	dba PoochyenaBitmasks
	dba MightyenaBitmasks
	dba WingullBitmasks
	dba PelipperBitmasks
	dba RaltsBitmasks
	dba KirliaBitmasks
	dba GardevoirBitmasks
	dba GalladeBitmasks
	dba ShroomishBitmasks
	dba BreloomBitmasks
	dba MakuhitaBitmasks
	dba HariyamaBitmasks
	dba SkittyBitmasks
	dba DelcattyBitmasks
	dba SableyeBitmasks
	dba MawileBitmasks
	dba AronBitmasks
	dba LaironBitmasks
	dba AggronBitmasks
	dba MedititeBitmasks
	dba MedichamBitmasks
	dba ElectrikeBitmasks
	dba ManectricBitmasks
	dba RoseliaBitmasks
	dba RoseradeBitmasks
	dba CarvanhaBitmasks
	dba SharpedoBitmasks
	dba NumelBitmasks
	dba CameruptBitmasks
	dba TorkoalBitmasks
	dba TrapinchBitmasks
	dba VibravaBitmasks
	dba FlygonBitmasks
	dba SwabluBitmasks
	dba AltariaBitmasks
	dba ZangooseBitmasks
	dba SeviperBitmasks
	dba LunatoneBitmasks
	dba SolrockBitmasks
	dba BarboachBitmasks
	dba WhiscashBitmasks
	dba CorphishBitmasks
	dba CrawdauntBitmasks
	dba BaltoyBitmasks
	dba ClaydolBitmasks
	dba LileepBitmasks
	dba CradilyBitmasks
	dba AnorithBitmasks
	dba ArmaldoBitmasks
	dba FeebasBitmasks
	dba MiloticBitmasks
	dba ShuppetBitmasks
	dba BanetteBitmasks
	dba DuskullBitmasks
	dba DusclopsBitmasks
	dba DusknoirBitmasks
	dba AbsolBitmasks
	dba SnoruntBitmasks
	dba GlalieBitmasks
	dba FroslassBitmasks
	dba SphealBitmasks
	dba SealeoBitmasks
	dba WalreinBitmasks
	dba BagonBitmasks
	dba ShelgonBitmasks
	dba SalamenceBitmasks
	dba BeldumBitmasks
	dba MetangBitmasks
	dba MetagrossBitmasks
	dba RegirockBitmasks
	dba RegiceBitmasks
	dba RegisteelBitmasks
	dba KyogreBitmasks
	dba GroudonBitmasks
	dba RayquazaBitmasks
	dba ShinxBitmasks
	dba LuxioBitmasks
	dba LuxrayBitmasks
	dba CranidosBitmasks
	dba RampardosBitmasks
	dba ShieldonBitmasks
	dba BastiodonBitmasks
	dba AmbipomBitmasks
	dba BunearyBitmasks
	dba LopunnyBitmasks
	dba MismagiusBitmasks
	dba HonchkrowBitmasks
	dba BronzorBitmasks
	dba BronzongBitmasks
	dba GibleBitmasks
	dba GabiteBitmasks
	dba RioluBitmasks
	dba LucarioBitmasks
	dba CroagunkBitmasks
	dba ToxicroakBitmasks
	dba SnoverBitmasks
	dba AbomasnowBitmasks
	dba WeavileBitmasks
	dba MagnezoneBitmasks
	dba LickilickyBitmasks
	dba RhyperiorBitmasks
	dba TangrowthBitmasks
	dba TogekissBitmasks
	dba YanmegaBitmasks
	dba LeafeonBitmasks
	dba GlaceonBitmasks
	dba GliscorBitmasks
	dba MamoswineBitmasks
	dba PorygonZBitmasks
	dba RegigigasBitmasks
	assert_table_length NUM_POKEMON
