DexAnimationPlanPointers:
	table_width 3
	dba BulbasaurDexAnimationPlan
	dba IvysaurDexAnimationPlan
	dba VenusaurDexAnimationPlan
	dba CharmanderDexAnimationPlan
	dba CharmeleonDexAnimationPlan
	dba CharizardDexAnimationPlan
	dba SquirtleDexAnimationPlan
	dba WartortleDexAnimationPlan
	dba BlastoiseDexAnimationPlan
	dba CaterpieDexAnimationPlan
	dba MetapodDexAnimationPlan
	dba ButterfreeDexAnimationPlan
	dba WeedleDexAnimationPlan
	dba KakunaDexAnimationPlan
	dba BeedrillDexAnimationPlan
	dba PidgeyDexAnimationPlan
	dba PidgeottoDexAnimationPlan
	dba PidgeotDexAnimationPlan
	dba RattataDexAnimationPlan
	dba RaticateDexAnimationPlan
	dba SpearowDexAnimationPlan
	dba FearowDexAnimationPlan
	dba EkansDexAnimationPlan
	dba ArbokDexAnimationPlan
	dba PikachuDexAnimationPlan
	dba RaichuDexAnimationPlan
	dba SandshrewDexAnimationPlan
	dba SandslashDexAnimationPlan
	dba NidoranFDexAnimationPlan
	dba NidorinaDexAnimationPlan
	dba NidoqueenDexAnimationPlan
	dba NidoranMDexAnimationPlan
	dba NidorinoDexAnimationPlan
	dba NidokingDexAnimationPlan
	dba ClefairyDexAnimationPlan
	dba ClefableDexAnimationPlan
	dba VulpixDexAnimationPlan
	dba NinetalesDexAnimationPlan
	dba JigglypuffDexAnimationPlan
	dba WigglytuffDexAnimationPlan
	dba ZubatDexAnimationPlan
	dba GolbatDexAnimationPlan
	dba OddishDexAnimationPlan
	dba GloomDexAnimationPlan
	dba VileplumeDexAnimationPlan
	dba ParasDexAnimationPlan
	dba ParasectDexAnimationPlan
	dba VenonatDexAnimationPlan
	dba VenomothDexAnimationPlan
	dba DiglettDexAnimationPlan
	dba DugtrioDexAnimationPlan
	dba MeowthDexAnimationPlan
	dba PersianDexAnimationPlan
	dba PsyduckDexAnimationPlan
	dba GolduckDexAnimationPlan
	dba MankeyDexAnimationPlan
	dba PrimeapeDexAnimationPlan
	dba GrowlitheDexAnimationPlan
	dba ArcanineDexAnimationPlan
	dba PoliwagDexAnimationPlan
	dba PoliwhirlDexAnimationPlan
	dba PoliwrathDexAnimationPlan
	dba AbraDexAnimationPlan
	dba KadabraDexAnimationPlan
	dba AlakazamDexAnimationPlan
	dba MachopDexAnimationPlan
	dba MachokeDexAnimationPlan
	dba MachampDexAnimationPlan
	dba BellsproutDexAnimationPlan
	dba WeepinbellDexAnimationPlan
	dba VictreebelDexAnimationPlan
	dba TentacoolDexAnimationPlan
	dba TentacruelDexAnimationPlan
	dba GeodudeDexAnimationPlan
	dba GravelerDexAnimationPlan
	dba GolemDexAnimationPlan
	dba PonytaDexAnimationPlan
	dba RapidashDexAnimationPlan
	dba SlowpokeDexAnimationPlan
	dba SlowbroDexAnimationPlan
	dba MagnemiteDexAnimationPlan
	dba MagnetonDexAnimationPlan
	dba FarfetchDDexAnimationPlan
	dba DoduoDexAnimationPlan
	dba DodrioDexAnimationPlan
	dba SeelDexAnimationPlan
	dba DewgongDexAnimationPlan
	dba GrimerDexAnimationPlan
	dba MukDexAnimationPlan
	dba ShellderDexAnimationPlan
	dba CloysterDexAnimationPlan
	dba GastlyDexAnimationPlan
	dba HaunterDexAnimationPlan
	dba GengarDexAnimationPlan
	dba OnixDexAnimationPlan
	dba DrowzeeDexAnimationPlan
	dba HypnoDexAnimationPlan
	dba KrabbyDexAnimationPlan
	dba KinglerDexAnimationPlan
	dba VoltorbDexAnimationPlan
	dba ElectrodeDexAnimationPlan
	dba ExeggcuteDexAnimationPlan
	dba ExeggutorDexAnimationPlan
	dba CuboneDexAnimationPlan
	dba MarowakDexAnimationPlan
	dba HitmonleeDexAnimationPlan
	dba HitmonchanDexAnimationPlan
	dba LickitungDexAnimationPlan
	dba KoffingDexAnimationPlan
	dba WeezingDexAnimationPlan
	dba RhyhornDexAnimationPlan
	dba RhydonDexAnimationPlan
	dba ChanseyDexAnimationPlan
	dba TangelaDexAnimationPlan
	dba KangaskhanDexAnimationPlan
	dba HorseaDexAnimationPlan
	dba SeadraDexAnimationPlan
	dba GoldeenDexAnimationPlan
	dba SeakingDexAnimationPlan
	dba StaryuDexAnimationPlan
	dba StarmieDexAnimationPlan
	dba MrMimeDexAnimationPlan
	dba ScytherDexAnimationPlan
	dba JynxDexAnimationPlan
	dba ElectabuzzDexAnimationPlan
	dba MagmarDexAnimationPlan
	dba PinsirDexAnimationPlan
	dba TaurosDexAnimationPlan
	dba MagikarpDexAnimationPlan
	dba GyaradosDexAnimationPlan
	dba LaprasDexAnimationPlan
	dba DittoDexAnimationPlan
	dba EeveeDexAnimationPlan
	dba VaporeonDexAnimationPlan
	dba JolteonDexAnimationPlan
	dba FlareonDexAnimationPlan
	dba PorygonDexAnimationPlan
	dba OmanyteDexAnimationPlan
	dba OmastarDexAnimationPlan
	dba KabutoDexAnimationPlan
	dba KabutopsDexAnimationPlan
	dba AerodactylDexAnimationPlan
	dba SnorlaxDexAnimationPlan
	dba ArticunoDexAnimationPlan
	dba ZapdosDexAnimationPlan
	dba MoltresDexAnimationPlan
	dba DratiniDexAnimationPlan
	dba DragonairDexAnimationPlan
	dba DragoniteDexAnimationPlan
	dba MewtwoDexAnimationPlan
	dba MewDexAnimationPlan
	dba ChikoritaDexAnimationPlan
	dba BayleefDexAnimationPlan
	dba MeganiumDexAnimationPlan
	dba CyndaquilDexAnimationPlan
	dba QuilavaDexAnimationPlan
	dba TyphlosionDexAnimationPlan
	dba TotodileDexAnimationPlan
	dba CroconawDexAnimationPlan
	dba FeraligatrDexAnimationPlan
	dba SentretDexAnimationPlan
	dba FurretDexAnimationPlan
	dba HoothootDexAnimationPlan
	dba NoctowlDexAnimationPlan
	dba LedybaDexAnimationPlan
	dba LedianDexAnimationPlan
	dba SpinarakDexAnimationPlan
	dba AriadosDexAnimationPlan
	dba CrobatDexAnimationPlan
	dba ChinchouDexAnimationPlan
	dba LanturnDexAnimationPlan
	dba PichuDexAnimationPlan
	dba CleffaDexAnimationPlan
	dba IgglybuffDexAnimationPlan
	dba TogepiDexAnimationPlan
	dba TogeticDexAnimationPlan
	dba NatuDexAnimationPlan
	dba XatuDexAnimationPlan
	dba MareepDexAnimationPlan
	dba FlaaffyDexAnimationPlan
	dba AmpharosDexAnimationPlan
	dba BellossomDexAnimationPlan
	dba MarillDexAnimationPlan
	dba AzumarillDexAnimationPlan
	dba SudowoodoDexAnimationPlan
	dba PolitoedDexAnimationPlan
	dba HoppipDexAnimationPlan
	dba SkiploomDexAnimationPlan
	dba JumpluffDexAnimationPlan
	dba AipomDexAnimationPlan
	dba SunkernDexAnimationPlan
	dba SunfloraDexAnimationPlan
	dba YanmaDexAnimationPlan
	dba WooperDexAnimationPlan
	dba QuagsireDexAnimationPlan
	dba EspeonDexAnimationPlan
	dba UmbreonDexAnimationPlan
	dba MurkrowDexAnimationPlan
	dba SlowkingDexAnimationPlan
	dba MisdreavusDexAnimationPlan
	dba UnownADexAnimationPlan
	dba WobbuffetDexAnimationPlan
	dba GirafarigDexAnimationPlan
	dba PinecoDexAnimationPlan
	dba ForretressDexAnimationPlan
	dba DunsparceDexAnimationPlan
	dba GligarDexAnimationPlan
	dba SteelixDexAnimationPlan
	dba SnubbullDexAnimationPlan
	dba GranbullDexAnimationPlan
	dba QwilfishDexAnimationPlan
	dba ScizorDexAnimationPlan
	dba ShuckleDexAnimationPlan
	dba HeracrossDexAnimationPlan
	dba SneaselDexAnimationPlan
	dba TeddiursaDexAnimationPlan
	dba UrsaringDexAnimationPlan
	dba SlugmaDexAnimationPlan
	dba MagcargoDexAnimationPlan
	dba SwinubDexAnimationPlan
	dba PiloswineDexAnimationPlan
	dba CorsolaDexAnimationPlan
	dba RemoraidDexAnimationPlan
	dba OctilleryDexAnimationPlan
	dba DelibirdDexAnimationPlan
	dba MantineDexAnimationPlan
	dba SkarmoryDexAnimationPlan
	dba HoundourDexAnimationPlan
	dba HoundoomDexAnimationPlan
	dba KingdraDexAnimationPlan
	dba PhanpyDexAnimationPlan
	dba DonphanDexAnimationPlan
	dba Porygon2DexAnimationPlan
	dba StantlerDexAnimationPlan
	dba SmeargleDexAnimationPlan
	dba TyrogueDexAnimationPlan
	dba HitmontopDexAnimationPlan
	dba SmoochumDexAnimationPlan
	dba ElekidDexAnimationPlan
	dba MagbyDexAnimationPlan
	dba MiltankDexAnimationPlan
	dba BlisseyDexAnimationPlan
	dba RaikouDexAnimationPlan
	dba EnteiDexAnimationPlan
	dba SuicuneDexAnimationPlan
	dba LarvitarDexAnimationPlan
	dba PupitarDexAnimationPlan
	dba TyranitarDexAnimationPlan
	dba LugiaDexAnimationPlan
	dba HoOhDexAnimationPlan
	dba CelebiDexAnimationPlan
	dba TreeckoDexAnimationPlan
	dba GrovyleDexAnimationPlan
	dba SceptileDexAnimationPlan
	dba TorchicDexAnimationPlan
	dba CombuskenDexAnimationPlan
	dba BlazikenDexAnimationPlan
	dba MudkipDexAnimationPlan
	dba MarshtompDexAnimationPlan
	dba SwampertDexAnimationPlan
	dba PoochyenaDexAnimationPlan
	dba MightyenaDexAnimationPlan
	dba WingullDexAnimationPlan
	dba PelipperDexAnimationPlan
	dba RaltsDexAnimationPlan
	dba KirliaDexAnimationPlan
	dba GardevoirDexAnimationPlan
	dba GalladeDexAnimationPlan
	dba ShroomishDexAnimationPlan
	dba BreloomDexAnimationPlan
	dba MakuhitaDexAnimationPlan
	dba HariyamaDexAnimationPlan
	dba SkittyDexAnimationPlan
	dba DelcattyDexAnimationPlan
	dba SableyeDexAnimationPlan
	dba MawileDexAnimationPlan
	dba AronDexAnimationPlan
	dba LaironDexAnimationPlan
	dba AggronDexAnimationPlan
	dba MedititeDexAnimationPlan
	dba MedichamDexAnimationPlan
	dba ElectrikeDexAnimationPlan
	dba ManectricDexAnimationPlan
	dba RoseliaDexAnimationPlan
	dba RoseradeDexAnimationPlan
	dba CarvanhaDexAnimationPlan
	dba SharpedoDexAnimationPlan
	dba NumelDexAnimationPlan
	dba CameruptDexAnimationPlan
	dba TorkoalDexAnimationPlan
	dba TrapinchDexAnimationPlan
	dba VibravaDexAnimationPlan
	dba FlygonDexAnimationPlan
	dba SwabluDexAnimationPlan
	dba AltariaDexAnimationPlan
	dba ZangooseDexAnimationPlan
	dba SeviperDexAnimationPlan
	dba LunatoneDexAnimationPlan
	dba SolrockDexAnimationPlan
	dba BarboachDexAnimationPlan
	dba WhiscashDexAnimationPlan
	dba CorphishDexAnimationPlan
	dba CrawdauntDexAnimationPlan
	dba BaltoyDexAnimationPlan
	dba ClaydolDexAnimationPlan
	dba LileepDexAnimationPlan
	dba CradilyDexAnimationPlan
	dba AnorithDexAnimationPlan
	dba ArmaldoDexAnimationPlan
	dba FeebasDexAnimationPlan
	dba MiloticDexAnimationPlan
	dba ShuppetDexAnimationPlan
	dba BanetteDexAnimationPlan
	dba DuskullDexAnimationPlan
	dba DusclopsDexAnimationPlan
	dba DusknoirDexAnimationPlan
	dba AbsolDexAnimationPlan
	dba SnoruntDexAnimationPlan
	dba GlalieDexAnimationPlan
	dba FroslassDexAnimationPlan
	dba SphealDexAnimationPlan
	dba SealeoDexAnimationPlan
	dba WalreinDexAnimationPlan
	dba BagonDexAnimationPlan
	dba ShelgonDexAnimationPlan
	dba SalamenceDexAnimationPlan
	dba BeldumDexAnimationPlan
	dba MetangDexAnimationPlan
	dba MetagrossDexAnimationPlan
	dba RegirockDexAnimationPlan
	dba RegiceDexAnimationPlan
	dba RegisteelDexAnimationPlan
	dba KyogreDexAnimationPlan
	dba GroudonDexAnimationPlan
	dba RayquazaDexAnimationPlan
	dba ShinxDexAnimationPlan
	dba LuxioDexAnimationPlan
	dba LuxrayDexAnimationPlan
	dba CranidosDexAnimationPlan
	dba RampardosDexAnimationPlan
	dba ShieldonDexAnimationPlan
	dba BastiodonDexAnimationPlan
	dba AmbipomDexAnimationPlan
	dba BunearyDexAnimationPlan
	dba LopunnyDexAnimationPlan
	dba MismagiusDexAnimationPlan
	dba HonchkrowDexAnimationPlan
	dba BronzorDexAnimationPlan
	dba BronzongDexAnimationPlan
	dba GibleDexAnimationPlan
	dba GabiteDexAnimationPlan
	dba GarchompDexAnimationPlan
	dba RioluDexAnimationPlan
	dba LucarioDexAnimationPlan
	dba SkorupiDexAnimationPlan
	dba DrapionDexAnimationPlan
	dba CroagunkDexAnimationPlan
	dba ToxicroakDexAnimationPlan
	dba SnoverDexAnimationPlan
	dba AbomasnowDexAnimationPlan
	dba WeavileDexAnimationPlan
	dba MagnezoneDexAnimationPlan
	dba LickilickyDexAnimationPlan
	dba RhyperiorDexAnimationPlan
	dba TangrowthDexAnimationPlan
	dba TogekissDexAnimationPlan
	dba YanmegaDexAnimationPlan
	dba LeafeonDexAnimationPlan
	dba GlaceonDexAnimationPlan
	dba GliscorDexAnimationPlan
	dba MamoswineDexAnimationPlan
	dba PorygonZDexAnimationPlan
	dba RegigigasDexAnimationPlan
	assert_table_length NUM_POKEMON

UnownDexAnimationPlanPointers:
	table_width 3
	dba UnownADexAnimationPlan
	dba UnownBDexAnimationPlan
	dba UnownCDexAnimationPlan
	dba UnownDDexAnimationPlan
	dba UnownEDexAnimationPlan
	dba UnownFDexAnimationPlan
	dba UnownGDexAnimationPlan
	dba UnownHDexAnimationPlan
	dba UnownIDexAnimationPlan
	dba UnownJDexAnimationPlan
	dba UnownKDexAnimationPlan
	dba UnownLDexAnimationPlan
	dba UnownMDexAnimationPlan
	dba UnownNDexAnimationPlan
	dba UnownODexAnimationPlan
	dba UnownPDexAnimationPlan
	dba UnownQDexAnimationPlan
	dba UnownRDexAnimationPlan
	dba UnownSDexAnimationPlan
	dba UnownTDexAnimationPlan
	dba UnownUDexAnimationPlan
	dba UnownVDexAnimationPlan
	dba UnownWDexAnimationPlan
	dba UnownXDexAnimationPlan
	dba UnownYDexAnimationPlan
	dba UnownZDexAnimationPlan
	assert_table_length NUM_UNOWN
