/* Host-only normal-input regression driver. No game RAM/ROM patch commands.
 * Linked symbol definitions and checkpoint tables are generated by cold_listing.py. */
#include "Core/gb.h"
#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static GB_gameboy_t gb;
static uint32_t pixels[160 * 144];
static uint64_t ticks;
static unsigned step_origin;
static bool auditing;

static uint32_t rgb(GB_gameboy_t *g, uint8_t r, uint8_t v, uint8_t b)
{
    (void)g;
    return (uint32_t)r << 16 | (uint32_t)v << 8 | b;
}

static unsigned byte(unsigned address)
{
    if (address >= 0xc000 && address < 0xd000) return gb.ram[address - 0xc000];
    return GB_read_memory(&gb, address);
}

static unsigned word(unsigned address)
{
    return byte(address) | byte(address + 1) << 8;
}

static bool at(unsigned bank, unsigned pc)
{
    return gb.pc == pc && (pc < 0x4000 || gb.mbc_rom_bank == bank) && !gb.halted;
}

static void hex(const uint8_t *p, unsigned length)
{
    putchar('"');
    for (unsigned i = 0; i < length; i++) printf("%02x", p[i]);
    putchar('"');
}

static void snapshot(int hit)
{
    unsigned index = word(S_wDexListingScrollOffset) + byte(S_wDexListingCursor);
    unsigned loaded = (word(S_wPokedexAnimDictionaryDestination) - 0xd000) / 16;
    unsigned sfx = byte(S_wChannel5Flags1) | byte(S_wChannel6Flags1) |
        byte(S_wChannel7Flags1) | byte(S_wChannel8Flags1);
    printf("{\"event\":\"stop\",\"hit\":%d,\"t\":%" PRIu64 ",\"pc\":%u,\"bank\":%u,"
           "\"index\":%u,\"scroll\":%u,\"cursor\":%u,\"end\":%u,\"mode\":%u,"
           "\"menu\":%u,\"jumptable\":%u,\"state\":%u,\"owner\":%u,\"loaded\":%u,"
           "\"upload\":%u,\"dictionary_services\":%u,\"upload_services\":%u,"
           "\"playback\":%u,\"audio\":%u,\"remaining\":%u,\"sfx\":%u,"
           "\"tick\":%u,\"joy\":%u,\"ly\":%u,\"ime\":%u,\"sp\":%u,\"double_speed\":%u,\"debug\":",
           hit, ticks / 2, gb.pc, gb.mbc_rom_bank, index,
           word(S_wDexListingScrollOffset), byte(S_wDexListingCursor), word(S_wDexListingEnd),
           byte(S_wCurDexMode), byte(S_wMenuCursorPosition), byte(S_wJumptableIndex),
           byte(S_wPokedexSelectedState), byte(S_wPokedexAnimOwner), loaded,
           byte(S_wPokedexAnimUploadOffset), byte(S_wPokedexAnimDebugDictionaryServices),
           byte(S_wPokedexAnimDebugUploadServices), byte(S_wPokedexAnimPlaybackState),
           byte(S_hSampledCryTimer), word(S_hSampledCryBlocks), sfx & 1,
           byte(S_hVBlankCounter), byte(S_hJoyDown), byte(0xff44), gb.ime, gb.sp, gb.cgb_double_speed);
    hex(gb.ram + S_wPokedexAnimDebug - 0xc000, S_wPokedexAnimDebugEnd - S_wPokedexAnimDebug);
    puts("}");
}

static void observe(GB_gameboy_t *g, uint16_t pc, uint8_t opcode)
{
    (void)g; (void)opcode;
    if (!auditing || gb.halted) return;
    /* Execution callbacks exclude IRQ dispatch that leaves the same PC pending.
     * Polling PC before GB_cpu_run would count that instruction twice. */
    uint64_t now = ticks + (unsigned)(gb.cycles_since_run - step_origin);
    unsigned bank = pc < 0x4000 ? 0 : gb.mbc_rom_bank;
    bool reveal = bank == B_REVEAL && pc == P_REVEAL;
    if (reveal || (bank == B_PUBLISH && pc == P_PUBLISH)) {
        uint8_t map[98], picture[49 * 16];
        for (unsigned y = 0; y < 7; y++) for (unsigned x = 0; x < 7; x++) {
            unsigned i = y * 7 + x, cell = 0x1821 + y * 32 + x;
            unsigned tile = gb.vram[cell], attr = gb.vram[0x2000 + cell];
            unsigned address = 0x1000 + (int8_t)tile * 16 + ((attr & 8) ? 0x2000 : 0);
            map[i] = tile; map[49 + i] = attr;
            for (unsigned row = 0; row < 8; row++) for (unsigned plane = 0; plane < 2; plane++) {
                uint8_t value = gb.vram[address + ((attr & 64) ? 7 - row : row) * 2 + plane];
                if (attr & 32) {
                    value = (value & 0x55) << 1 | (value >> 1 & 0x55);
                    value = (value & 0x33) << 2 | (value >> 2 & 0x33);
                    value = value << 4 | value >> 4;
                }
                picture[i * 16 + row * 2 + plane] = value;
            }
        }
        printf("{\"event\":\"%s\",\"t\":%" PRIu64 ",\"tick\":%u,\"frame\":%u,"
               "\"slot\":%u,\"ordinal\":%u,\"ly\":%u,\"map\":", reveal ? "reveal" : "publish", now / 2,
               (byte(S_hVBlankCounter) + 1) & 255, byte(S_wPokedexAnimStageFrameID),
               byte(S_wPokedexAnimStageSlot), byte(S_wPokedexAnimDebugEventReads), byte(0xff44));
        hex(map, sizeof(map)); printf(",\"picture\":"); hex(picture, sizeof(picture)); puts("}");
    }
    if (bank == B_ANIMATION_MISS && pc == P_ANIMATION_MISS) {
        printf("{\"event\":\"animation_miss\",\"t\":%" PRIu64 "}\n", now / 2);
    }
    if (bank == B_AUDIO_EMPTY && pc == P_AUDIO_EMPTY) {
        printf("{\"event\":\"audio_miss\",\"t\":%" PRIu64 ",\"remaining\":%u}\n",
               now / 2, word(S_hSampledCryBlocks));
    }
    if (bank == B_AUDIO_STOP && pc == P_AUDIO_STOP && byte(S_hSampledCryTimer)) {
        printf("{\"event\":\"audio_stop\",\"t\":%" PRIu64 ",\"remaining\":%u}\n",
               now / 2, word(S_hSampledCryBlocks));
    }
}

int main(int argc, char **argv)
{
    if (argc != 4) { fprintf(stderr, "Usage: cold-listing ROM BOOT_ROM BATTERY_COPY\n"); return 2; }
    GB_init(&gb, GB_MODEL_CGB_E);
    GB_set_turbo_mode(&gb, true, true);
    GB_set_pixels_output(&gb, pixels);
    GB_set_rgb_encode_callback(&gb, rgb);
    GB_set_execution_callback(&gb, observe);
    if (GB_load_rom(&gb, argv[1]) || GB_load_boot_rom(&gb, argv[2]) ||
        GB_load_battery(&gb, argv[3])) return 2;
    setvbuf(stdout, NULL, _IOLBF, 0);
    char line[4096];
    while (fgets(line, sizeof(line), stdin)) {
        unsigned keys; uint64_t mask, budget;
        if (sscanf(line, "run %" SCNu64 " %" SCNu64 " %u", &mask, &budget, &keys) == 3) {
            GB_set_key_mask(&gb, keys);
            uint64_t start = ticks;
            int hit = -1;
            do {
                unsigned before = gb.cycles_since_run;
                step_origin = before;
                GB_cpu_run(&gb);
                ticks += (unsigned)(gb.cycles_since_run - before);
                for (unsigned i = 0; i < sizeof(points) / sizeof(*points); i++) {
                    if ((mask & (UINT64_C(1) << i)) && at(points[i].bank, points[i].pc)) { hit = i; break; }
                }
            } while (hit < 0 && ticks - start < budget * 2);
            snapshot(hit);
        } else if (!strcmp(line, "peek\n")) {
            snapshot(-1);
        } else if (sscanf(line, "audit %u", &keys) == 1) {
            auditing = keys != 0;
            puts("{\"event\":\"ok\"}");
        } else if (!strncmp(line, "save ", 5) || !strncmp(line, "load ", 5)) {
            line[strcspn(line, "\r\n")] = 0;
            bool save = line[0] == 's';
            int result = save ? GB_save_state(&gb, line + 5) : GB_load_state(&gb, line + 5);
            if (!save) ticks = 0;
            printf("{\"event\":\"ok\",\"error\":%d}\n", result);
        } else if (!strncmp(line, "image ", 6)) {
            line[strcspn(line, "\r\n")] = 0;
            FILE *file = fopen(line + 6, "wb");
            if (!file) return 2;
            fprintf(file, "P6\n160 144\n255\n");
            for (unsigned i = 0; i < 160 * 144; i++) {
                uint8_t p[] = {pixels[i] >> 16, pixels[i] >> 8, pixels[i]};
                fwrite(p, 1, 3, file);
            }
            int result = fclose(file);
            printf("{\"event\":\"ok\",\"error\":%d}\n", result);
        } else if (!strcmp(line, "quit\n")) break;
        else { fprintf(stderr, "Unknown host command\n"); return 2; }
    }
    GB_free(&gb);
    return 0;
}
