/* Host-only normal-input regression driver. No game RAM/ROM patch commands.
 * Linked symbol definitions and checkpoint tables are generated by cold_listing.py. */
#include "Core/gb.h"
#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static GB_gameboy_t gb;
static uint32_t pixels[160 * 144];
static uint64_t ticks;
static unsigned step_origin;
static bool auditing;
/* Observer-owned counters: no writes to the game's former trace storage. */
static unsigned dictionary_services, upload_services, publications;

static uint32_t rgb(GB_gameboy_t *g, uint8_t r, uint8_t v, uint8_t b)
{
    (void)g;
    return (uint32_t)r << 16 | (uint32_t)v << 8 | b;
}

static unsigned byte(unsigned address)
{
    if (address >= 0xc000 && address < 0xd000) return gb.ram[address - 0xc000];
    if (address >= 0xff80 && address < 0xffff) return gb.hram[address - 0xff80];
    if (address >= 0xff00 && address < 0xff80) return gb.io_registers[address - 0xff00];
    if (address >= 0xd000 && address < 0xe000)
        return gb.ram[gb.cgb_ram_bank * 4096 + (address & 4095)];
    fprintf(stderr,"Unsupported observation address: %04x\n",address);exit(11);
}

static unsigned word(unsigned address)
{
    return byte(address) | byte(address + 1) << 8;
}

static bool at(unsigned bank, unsigned pc)
{
    return gb.pc == pc && (pc < 0x4000 || gb.mbc_rom_bank == bank) && !gb.halted;
}

static void hex(const uint8_t *p, unsigned length)
{
    putchar('"');
    for (unsigned i = 0; i < length; i++) printf("%02x", p[i]);
    putchar('"');
}

#ifdef DEX_LISTING_RESTORE_TRACE
#include "listing_restoration.c"
#endif
#ifdef DEX_CRY_OWNER_TRACE
#include "cry_ownership.c"
#endif
#ifdef DEX_DIRECTION_CHANGE_TRACE
#include "direction_changes.c"
#endif
#ifdef SHARED_MENU_INPUT_TRACE
#include "shared_menu_input.c"
#endif

static void snapshot(int hit)
{
    unsigned index = word(S_wDexListingScrollOffset) + byte(S_wDexListingCursor);
    unsigned loaded = (word(S_wPokedexAnimDictionaryDestination) - 0xd000) / 16;
    unsigned sfx = byte(S_wChannel5Flags1) | byte(S_wChannel6Flags1) |
        byte(S_wChannel7Flags1) | byte(S_wChannel8Flags1);
    printf("{\"event\":\"stop\",\"hit\":%d,\"t\":%" PRIu64 ",\"pc\":%u,\"bank\":%u,"
           "\"index\":%u,\"scroll\":%u,\"cursor\":%u,\"end\":%u,\"mode\":%u,"
           "\"menu\":%u,\"jumptable\":%u,\"state\":%u,\"owner\":%u,\"loaded\":%u,"
           "\"upload\":%u,\"dictionary_services\":%u,\"upload_services\":%u,"
           "\"playback\":%u,\"audio\":%u,\"remaining\":%u,\"sfx\":%u,"
           "\"tick\":%u,\"joy\":%u,\"ly\":%u,\"ime\":%u,\"sp\":%u,\"double_speed\":%u",
           hit, ticks / 2, gb.pc, gb.mbc_rom_bank, index,
           word(S_wDexListingScrollOffset), byte(S_wDexListingCursor), word(S_wDexListingEnd),
           byte(S_wCurDexMode), byte(S_wMenuCursorPosition), byte(S_wJumptableIndex),
           byte(S_wPokedexSelectedState), byte(S_wPokedexAnimOwner), loaded,
           byte(S_wPokedexAnimUploadOffset), dictionary_services,
           upload_services, byte(S_wPokedexAnimPlaybackState),
           byte(S_hSampledCryTimer), word(S_hSampledCryBlocks), sfx & 1,
           byte(S_hVBlankCounter), byte(S_hJoyDown), byte(0xff44), gb.ime, gb.sp, gb.cgb_double_speed);
    printf(",\"selected_index\":%u}\n", word(S_wPokedexSelectedIndex));
}

static void observe(GB_gameboy_t *g, uint16_t pc, uint8_t opcode)
{
    (void)g; (void)opcode;
    if (gb.halted) return;
    /* Execution callbacks exclude IRQ dispatch that leaves the same PC pending.
     * Polling PC before GB_cpu_run would count that instruction twice. */
    uint64_t now = ticks + (unsigned)(gb.cycles_since_run - step_origin);
    unsigned bank = pc < 0x4000 ? 0 : gb.mbc_rom_bank;
#ifdef DEX_LISTING_RESTORE_TRACE
    restoration_observe(bank, pc);
#endif
#ifdef DEX_CRY_OWNER_TRACE
    cry_owner_observe(bank, pc);
#endif
#ifdef DEX_DIRECTION_CHANGE_TRACE
    direction_observe(bank, pc);
#endif
#ifdef SHARED_MENU_INPUT_TRACE
    shared_menu_observe(bank, pc);
#endif
    if (bank==B_INIT && pc==P_INIT) dictionary_services=upload_services=publications=0;
    if (bank==B_DECODE && pc==P_DECODE) dictionary_services++;
    if (bank==B_UPLOAD && pc==P_UPLOAD) upload_services++;
    if (bank==B_BEGIN && pc==P_BEGIN) publications=0;
    if (!auditing) return;
    bool reveal = (bank == B_REVEAL && pc == P_REVEAL) ||
        (bank == B_PAGE_REVEAL && pc == P_PAGE_REVEAL);
    if (reveal || (bank == B_PUBLISH && pc == P_PUBLISH)) {
        uint8_t map[98], picture[49 * 16];
        for (unsigned y = 0; y < 7; y++) for (unsigned x = 0; x < 7; x++) {
            unsigned i = y * 7 + x, cell = 0x1821 + y * 32 + x;
            unsigned tile = gb.vram[cell], attr = gb.vram[0x2000 + cell];
            unsigned address = 0x1000 + (int8_t)tile * 16 + ((attr & 8) ? 0x2000 : 0);
            map[i] = tile; map[49 + i] = attr;
            for (unsigned row = 0; row < 8; row++) for (unsigned plane = 0; plane < 2; plane++) {
                uint8_t value = gb.vram[address + ((attr & 64) ? 7 - row : row) * 2 + plane];
                if (attr & 32) {
                    value = (value & 0x55) << 1 | (value >> 1 & 0x55);
                    value = (value & 0x33) << 2 | (value >> 2 & 0x33);
                    value = value << 4 | value >> 4;
                }
                picture[i * 16 + row * 2 + plane] = value;
            }
        }
        printf("{\"event\":\"%s\",\"t\":%" PRIu64 ",\"tick\":%u,\"frame\":%u,"
               "\"slot\":%u,\"ordinal\":%u,\"ly\":%u,\"map\":", reveal ? "reveal" : "publish", now / 2,
               (byte(S_hVBlankCounter) + 1) & 255, byte(S_wPokedexAnimStageFrameID),
               byte(S_wPokedexAnimStageSlot), reveal ? 0 : ++publications, byte(0xff44));
        hex(map, sizeof(map)); printf(",\"picture\":"); hex(picture, sizeof(picture)); puts("}");
    }
    if (bank == B_ANIMATION_MISS && pc == P_ANIMATION_MISS) {
        printf("{\"event\":\"animation_miss\",\"t\":%" PRIu64 "}\n", now / 2);
    }
    if (bank == B_AUDIO_EMPTY && pc == P_AUDIO_EMPTY) {
        printf("{\"event\":\"audio_miss\",\"t\":%" PRIu64 ",\"remaining\":%u}\n",
               now / 2, word(S_hSampledCryBlocks));
    }
    if (bank == B_AUDIO_STOP && pc == P_AUDIO_STOP && byte(S_hSampledCryTimer)) {
        printf("{\"event\":\"audio_stop\",\"t\":%" PRIu64 ",\"remaining\":%u}\n",
               now / 2, word(S_hSampledCryBlocks));
    }
}

int main(int argc, char **argv)
{
    if (argc != 4) { fprintf(stderr, "Usage: cold-listing ROM BOOT_ROM BATTERY_COPY\n"); return 2; }
    GB_init(&gb, GB_MODEL_CGB_E);
    GB_set_turbo_mode(&gb, true, true);
    GB_set_pixels_output(&gb, pixels);
    GB_set_rgb_encode_callback(&gb, rgb);
    GB_set_execution_callback(&gb, observe);
#ifdef DEX_LISTING_RESTORE_TRACE
    GB_set_vblank_callback(&gb, restoration_frame);
    GB_set_write_memory_callback(&gb, restoration_write);
    GB_set_lcd_line_callback(&gb, restoration_line);
#endif
    if (GB_load_rom(&gb, argv[1]) || GB_load_boot_rom(&gb, argv[2]) ||
        GB_load_battery(&gb, argv[3])) return 2;
    setvbuf(stdout, NULL, _IOLBF, 0);
    char line[4096];
    while (fgets(line, sizeof(line), stdin)) {
        unsigned keys; uint64_t mask, budget;
        if (sscanf(line, "run %" SCNu64 " %" SCNu64 " %u", &mask, &budget, &keys) == 3) {
            GB_set_key_mask(&gb, keys);
#ifdef DEX_DIRECTION_CHANGE_TRACE
            direction_input(keys);
#endif
            uint64_t start = ticks;
            int hit = -1;
            do {
                unsigned before = gb.cycles_since_run;
                step_origin = before;
                GB_cpu_run(&gb);
                ticks += (unsigned)(gb.cycles_since_run - before);
                for (unsigned i = 0; i < sizeof(points) / sizeof(*points); i++) {
                    if ((mask & (UINT64_C(1) << i)) && at(points[i].bank, points[i].pc)) { hit = i; break; }
                }
            } while (hit < 0 && ticks - start < budget * 2);
            snapshot(hit);
        }
#ifdef DEX_LISTING_RESTORE_TRACE
        else if (restoration_command(line)) {
            /* Optional host-only diagnostic commands never change game memory. */
        }
#endif
#ifdef DEX_CRY_OWNER_TRACE
        else if (cry_owner_command(line)) {
            /* Read-only ownership snapshots in the diagnostic executable. */
        }
#endif
#ifdef DEX_DIRECTION_CHANGE_TRACE
        else if (direction_command(line)) {
            /* Read-only input snapshots in the diagnostic executable. */
        }
#endif
#ifdef SHARED_MENU_INPUT_TRACE
        else if (shared_menu_command(line)) {
            /* Physical input and read-only snapshots in a private test core. */
        }
#endif
        else if (!strcmp(line, "peek\n")) {
            snapshot(-1);
        } else if (!strcmp(line, "ui\n")) {
            uint8_t map[21 * 18], attrs[21 * 18];
            for (unsigned y = 0; y < 18; y++) for (unsigned x = 0; x < 21; x++) {
                map[y * 21 + x] = gb.vram[0x1800 + y * 32 + x];
                attrs[y * 21 + x] = gb.vram[0x3800 + y * 32 + x];
            }
            printf("{\"event\":\"ok\",\"view\":%u,\"page\":%u,\"types\":[%u,%u],\"map\":",
                   byte(S_wPokedexSelectedView), byte(S_wPokedexDescriptionPage),
                   gb.ram[0x1000 + (S_wBaseType1 & 4095)],
                   gb.ram[0x1000 + (S_wBaseType2 & 4095)]);
            hex(map, sizeof(map)); printf(",\"attrs\":"); hex(attrs, sizeof(attrs));
            printf(",\"palettes\":"); hex(gb.background_palettes_data, 64);
            printf(",\"border_gfx\":"); hex(gb.vram + 0x1710, 10 * 16);
            unsigned type_cell = 7 * 21 + 9, foot_cell = 21 + 18;
            unsigned type_address = 0x1000 + (int8_t)map[type_cell] * 16;
            unsigned foot_address = 0x1000 + (int8_t)map[foot_cell] * 16;
            if (attrs[type_cell] & 8) type_address += 0x2000;
            if (attrs[foot_cell] & 8) foot_address += 0x2000;
            printf(",\"type_gfx\":"); hex(gb.vram + type_address, 8 * 16);
            printf(",\"footprint_gfx\":"); hex(gb.vram + foot_address, 4 * 16); puts("}");
        } else if (!strcmp(line, "rawcolor\n")) {
            GB_set_color_correction_mode(&gb, GB_COLOR_CORRECTION_DISABLED);
            puts("{\"event\":\"ok\"}");
        } else if (sscanf(line, "audit %u", &keys) == 1) {
            auditing = keys != 0;
            puts("{\"event\":\"ok\"}");
        } else if (!strncmp(line, "save ", 5) || !strncmp(line, "load ", 5)) {
            line[strcspn(line, "\r\n")] = 0;
            bool save = line[0] == 's';
            int result = save ? GB_save_state(&gb, line + 5) : GB_load_state(&gb, line + 5);
            if (!save) { ticks = 0; dictionary_services=upload_services=publications=0; }
            printf("{\"event\":\"ok\",\"error\":%d}\n", result);
        } else if (!strncmp(line, "image ", 6)) {
            line[strcspn(line, "\r\n")] = 0;
            FILE *file = fopen(line + 6, "wb");
            if (!file) return 2;
            fprintf(file, "P6\n160 144\n255\n");
            for (unsigned i = 0; i < 160 * 144; i++) {
                uint8_t p[] = {pixels[i] >> 16, pixels[i] >> 8, pixels[i]};
                fwrite(p, 1, 3, file);
            }
            int result = fclose(file);
            printf("{\"event\":\"ok\",\"error\":%d}\n", result);
        } else if (!strcmp(line, "quit\n")) break;
        else { fprintf(stderr, "Unknown host command\n"); return 2; }
    }
#ifdef DEX_LISTING_RESTORE_TRACE
    restoration_close();
#endif
#ifdef DEX_CRY_OWNER_TRACE
    cry_owner_close();
#endif
#ifdef DEX_DIRECTION_CHANGE_TRACE
    direction_close();
#endif
#ifdef SHARED_MENU_INPUT_TRACE
    shared_menu_close();
#endif
    GB_free(&gb);
    return 0;
}
