"""Compile static Dex Area landmarks from the native encounter sources.

Roamers stay live at runtime. Generated files belong in ignored build output,
and no linked ROM or prototype checkout is required to regenerate them.
"""
import argparse
from pathlib import Path
import re

from pokedex_info_assets import constants, species

ROOT = Path(__file__).resolve().parents[1]


def lines(path):
    return [line.split(';', 1)[0].strip() for line in path.read_text().splitlines()]


def map_landmarks(root):
    groups, current = [], None
    for line in lines(root / 'constants/map_constants.asm'):
        if re.fullmatch(r'newgroup \w+', line):
            current = []
            groups.append(current)
        elif match := re.match(r'map_const (\w+),', line):
            current.append(match[1])
    headers = []
    for line in lines(root / 'data/maps/maps.asm'):
        if re.fullmatch(r'MapGroup_\w+:', line):
            headers.append([])
        elif line.startswith('map '):
            fields = [field.strip() for field in line[4:].split(',')]
            if len(fields) != 8:
                raise ValueError(f'Unsupported map header: {line}')
            headers[-1].append((fields[0], fields[3]))
    if len(groups) != len(headers):
        raise ValueError('Map constants and header groups disagree')
    result = {}
    for group, header in zip(groups, headers):
        if len(group) != len(header):
            raise ValueError('Map constants and header counts disagree')
        for name, (label, landmark) in zip(group, header):
            if name.replace('_', '').lower() != label.replace('_', '').lower():
                raise ValueError(f'Map ordering disagreement: {name}, {label}')
            result[name] = landmark
    return result


def encounters(path, kind):
    result, current = [], None
    slots = 21 if kind == 'grass' else 3
    for line in lines(path):
        if match := re.fullmatch(rf'def_{kind}_wildmons (\w+)', line):
            if current is not None:
                raise ValueError(f'Unterminated encounter record in {path}')
            current = (match[1], [])
        elif line.startswith('dbwbb '):
            fields = [field.strip() for field in line[6:].split(',')]
            if current is None or len(fields) != 4:
                raise ValueError(f'Unsupported encounter record: {line}')
            current[1].append(fields[1])
        elif line == f'end_{kind}_wildmons':
            if current is None or len(current[1]) != slots:
                raise ValueError(f'Expected {slots} encounter slots in {path}: {current}')
            result.append(current)
            current = None
    if current is not None:
        raise ValueError(f'Unterminated encounter record in {path}')
    return result


def compile_assets(root=ROOT):
    names = species(root)
    known = set(names)
    landmarks = map_landmarks(root)
    values = constants(root / 'constants/landmark_constants.asm')
    nests = {(name, region): [] for name in names for region in range(2)}
    for region, label in enumerate(('johto', 'kanto')):
        for kind in ('grass', 'water'):
            for map_name, entries in encounters(root / f'data/wild/{label}_{kind}.asm', kind):
                landmark = values[landmarks[map_name]]
                for name in dict.fromkeys(entries):
                    if name not in known:
                        raise ValueError(f'Unknown encounter species: {name}')
                    target = nests[name, region]
                    if landmark not in target:
                        target.append(landmark)
    table = ['; Generated by tools/pokedex_area_assets.py. Do not edit.', 'PokedexPerf_NestIndex:']
    for name in names:
        table.append(f'\tdw PokedexPerf_Nest_{name}_0, PokedexPerf_Nest_{name}_1')
    for name in names:
        for region in range(2):
            locations = nests[name, region]
            if len(locations) > 255:
                raise ValueError(f'Area landmark count exceeds one byte: {name}')
            table.extend((f'PokedexPerf_Nest_{name}_{region}:',
                          '\tdb ' + ', '.join(map(str, [len(locations), *locations]))))
    palettes = constants(root / 'gfx/pokegear/town_map_palette_map.asm')
    expanded = []
    for line in lines(root / 'gfx/pokegear/town_map_palette_map.asm'):
        if line.startswith('townmappals '):
            expanded.extend(palettes['PAL_TOWNMAP_' + p.strip()] & 7 for p in line[12:].split(','))
    if len(expanded) != 96:
        raise ValueError('Town Map palette source must describe 96 tiles')
    return '\n'.join(table) + '\n', bytes(expanded + [0] * 160), nests


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, default=ROOT)
    parser.add_argument('--output', type=Path, default=ROOT / 'build/dex-area-assets')
    args = parser.parse_args()
    table, palettes, _ = compile_assets(args.root)
    args.output.mkdir(parents=True, exist_ok=True)
    (args.output / 'tables.asm').write_text(table)
    (args.output / 'town-pals.bin').write_bytes(palettes)


if __name__ == '__main__':
    main()
